/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type PromptVariables__test__0_0_1 = never;
export type PromptConfig__test__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__test__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__test__0_0_1;
  variables: PromptVariables__test__0_0_1;
  content: string;
};
export type Prompt__test = {
  name: 'test';
  slug: 'test';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__test__0_0_1;
  };
};
export type Globals = {};
export type Agency = {
  prompts: {
    test: Prompt__test;
  };
  globals: Globals;
};
